library(peer)
expr = read.csv('./peer_input.csv', header=FALSE)
model = PEER()
PEER_setPhenoMean(model,as.matrix(expr))
PEER_setNk(model,10)
PEER_getNk(model)
PEER_update(model)
factors = PEER_getX(model)
write.table(factors,"exp.peer.factors_new.txt",quote=F,row.names=F,col.names=F,sep="\t")